export interface BacktestFieldHelp {
  id: string;
  title: string;
  whatItMeans: string;
  whyItMatters: string;
  howToUse: string[];
  recommendedDefault: string;
  withoutIt: string;
  bestPractices: string[];
}

export const backtestFieldHelp: Record<string, BacktestFieldHelp> = {
  instrumentType: {
    id: "instrumentType",
    title: "Instrument Type",
    whatItMeans: "Volba trzniho segmentu, pro ktery se maji nacist data a pravidla vypoctu PnL.",
    whyItMatters: "Kazdy trh ma jinou mikrostrukturu a odlisny model nakladu.",
    howToUse: [
      "Pro index futures pouzij `futures`.",
      "Pro jednotlive akcie pouzij `stocks`.",
      "Pro FX pary pouzij `forex` a nastav lot/pip parametry.",
    ],
    recommendedDefault: "Zacni na trhu, ktery opravdu obchodujes (typicky futures).",
    withoutIt: "Muzes pouzivat spatny cenovy model a dostat nerealne vysledky.",
    bestPractices: ["Nemixuj typy trhu v jednom baseline runu.", "Pri zmene typu zkontroluj instrument config."],
  },
  instrument: {
    id: "instrument",
    title: "Instrument",
    whatItMeans: "Konretni symbol s historickymi daty (napr. NQ, ES).",
    whyItMatters: "Strategie muze fungovat na jednom trhu a selhavat na jinem.",
    howToUse: [
      "Vyber symbol, pro ktery mas realistickou obchodni hypotezu.",
      "Over, ze delka dostupnych dat pokryva tvoje testovaci obdobi.",
    ],
    recommendedDefault: "Pouzij hlavni trh strategie, ne nahodny symbol.",
    withoutIt: "Nebudes vedet, jestli edge opravdu patri k zamyslenemu trhu.",
    bestPractices: ["Pro porovnani trhu del samostatne branche."],
  },
  years: {
    id: "years",
    title: "Delka backtestu (roky)",
    whatItMeans: "Pocet let historie, ktere vstupuji do simulace.",
    whyItMatters: "Maly vzorek casto nadhodnocuje vykon a podhodnocuje drawdown.",
    howToUse: [
      "Pouzij minimalne tolik dat, aby strategie prosla vice trznimi rezimy.",
      "U kratkych intradennich edge je vhodna delsi historie.",
    ],
    recommendedDefault: "1-3 roky pro prvni iterace, vice pro finalni validaci.",
    withoutIt: "Hrozi, ze test zachyti jen prizenive obdobi trhu.",
    bestPractices: ["Pri zaverecnem hodnoceni testuj delsi horizont nez pri rychlem prototypu."],
  },
  tickSize: {
    id: "tickSize",
    title: "Tick Size",
    whatItMeans: "Minimalni cenovy krok futures kontraktu.",
    whyItMatters: "PnL i fill logika jsou zavisle na spravne granularite ceny.",
    howToUse: ["Nastav podle specifikace kontraktu brokera/exchange."],
    recommendedDefault: "NQ typicky 0.25.",
    withoutIt: "Backtest muze pocitat neexistujici ceny a zkreslit vysledky.",
    bestPractices: ["Pri zmene instrumentu tick size vzdy znovu over."],
  },
  valuePerTick: {
    id: "valuePerTick",
    title: "Value Per Tick (USD)",
    whatItMeans: "Kolik penez odpovida jednomu ticku pohybu ceny.",
    whyItMatters: "Primo urcuje velikost zisku/ztraty na obchod.",
    howToUse: ["Nastav dle kontraktovych specifikaci."],
    recommendedDefault: "NQ typicky 5 USD na tick.",
    withoutIt: "PnL bude v nespravne menove skale.",
    bestPractices: ["Vzdy validuj s realnymi contract specs."],
  },
  shareSize: {
    id: "shareSize",
    title: "Position Size (stocks)",
    whatItMeans: "Pocet akcii na obchod.",
    whyItMatters: "Riziko i navratnost jsou linearne zavisle na velikosti pozice.",
    howToUse: ["Nastav konzistentni velikost nebo navaz na risk model."],
    recommendedDefault: "100 akcii pro jednoduchy baseline.",
    withoutIt: "Srovnani runu bude nepresne kvuli rozdilne expozici.",
    bestPractices: ["Nemen size pri kazdem runu bez evidovaneho duvodu."],
  },
  lotSize: {
    id: "lotSize",
    title: "Lot Size (forex)",
    whatItMeans: "Objem obchodu ve forexe.",
    whyItMatters: "Urcuje nominalni expozici a citlivost na pip pohyb.",
    howToUse: ["Nastav podle pravidel risk managementu."],
    recommendedDefault: "1 lot jen pokud odpovida tvemu kapitalu; jinak mensi.",
    withoutIt: "Strategie muze vypadat nerealne agresivne nebo naopak prilis slabe.",
    bestPractices: ["Drz konzistentni risk na obchod napric runy."],
  },
  pipSize: {
    id: "pipSize",
    title: "Pip Size",
    whatItMeans: "Minimalni jednotka pohybu ceny pro forex par.",
    whyItMatters: "Ovlivnuje prepocet z cenoveho pohybu na pips a PnL.",
    howToUse: ["Nastav podle daneho paru (casto 0.0001, nekdy 0.01)."],
    recommendedDefault: "0.0001 pro vetsinu major paru.",
    withoutIt: "PnL metriky budou matematicky posunute.",
    bestPractices: ["U JPY paru over pip convention separatne."],
  },
  pipValue: {
    id: "pipValue",
    title: "Pip Value (USD)",
    whatItMeans: "Hodnota jednoho pipu v dolarech pri zvolenem lotu.",
    whyItMatters: "Urcuje citlivost equity na pohyb ceny.",
    howToUse: ["Nastav konzistentne s lotSize a menovym parem."],
    recommendedDefault: "10 USD je bezny orientacni baseline pro standard lot.",
    withoutIt: "Risk model nebude odpovidat realite.",
    bestPractices: ["Po zmene lotSize prepocitej i pipValue."],
  },
  initialCapital: {
    id: "initialCapital",
    title: "Pocatecni kapital",
    whatItMeans: "Startovni equity pro simulaci.",
    whyItMatters: "Ovlivnuje relativni metriky i odolnost strategie v drawdownu.",
    howToUse: ["Nastav realisticky kapital, se kterym bys strategii spoustel."],
    recommendedDefault: "100000 jako neutralni baseline pro porovnani.",
    withoutIt: "Srovnani runu bude matouci kvuli jine skale equity.",
    bestPractices: ["Nemen kapital mezi testy, pokud zrovna netestujes position sizing."],
  },
  slippagePerc: {
    id: "slippagePerc",
    title: "Slippage (%)",
    whatItMeans: "Prumerny skluz mezi ocekavanou a skutecnou fill cenou.",
    whyItMatters: "Bez slippage byva backtest nadhodnoceny oproti live exekuci.",
    howToUse: ["Nastav konzervativni odhad podle likvidity trhu a stylu vstupu."],
    recommendedDefault: "0.05%-0.15% podle trhu a timeframe.",
    withoutIt: "Hrozi optimistic bias, hlavne u rychlych strategii.",
    bestPractices: ["U volatilnich trhu testuj i horsi variantu slippage."],
  },
  commissionPerc: {
    id: "commissionPerc",
    title: "Komise (%)",
    whatItMeans: "Transakcni naklad za vstup/vystup obchodu.",
    whyItMatters: "Mala komise muze znicit edge u casto obchodujicich strategii.",
    howToUse: ["Zadej realnou uroven fee od brokera plus burzovni poplatky."],
    recommendedDefault: "Konzervativni realna hodnota, ne nula.",
    withoutIt: "Vyjde ti nerealne vysoky profit factor i cisty zisk.",
    bestPractices: ["Nejdriv testuj s realnymi fee, az pak optimalizuj logiku."],
  },
  selectedIndicatorIds: {
    id: "selectedIndicatorIds",
    title: "Indikatory",
    whatItMeans: "Seznam indikatoru, ktere se maji zahrnout do backtestu.",
    whyItMatters: "Nepotvrzene nebo nevybrane indikatory se do runu nepromitnou.",
    howToUse: [
      "Zaskrtni indikatory, ktere strategie vyzaduje.",
      "Po zmene vyberu klikni na Potvrdit.",
    ],
    recommendedDefault: "Pouzit jen indikatory, ktere strategie skutecne importuje.",
    withoutIt: "Backtest muze bezet bez potrebnych vypoctu nebo s jinou logikou.",
    bestPractices: ["Drz vyber minimalni a transparentni."],
  },
  selectedModuleIds: {
    id: "selectedModuleIds",
    title: "Moduly",
    whatItMeans: "Seznam modulu, jejichz vystupy a parametry se pouziji v runu.",
    whyItMatters: "Moduly casto nesou kontext (zony, markery), bez ktereho je signal nekompletni.",
    howToUse: [
      "Vyber relevantni moduly a potvrd vyber.",
      "Zkontroluj jejich VIEW_PARAMS v sekci Parameters.",
    ],
    recommendedDefault: "Zacni 1-2 moduly, ne vsechny najednou.",
    withoutIt: "Muzes testovat jinou strategii, nez sis myslel.",
    bestPractices: ["Pri pridani noveho modulu over nejdriv View mode."],
  },
  validationMode: {
    id: "validationMode",
    title: "Validation mode",
    whatItMeans: "Rezim overeni robustnosti strategie (single, OOS split, walk-forward).",
    whyItMatters: "Je to nejdulezitejsi obrana proti overfittingu.",
    howToUse: [
      "Single run pouzij jen na rychle smoke testy.",
      "OOS split je dobre minimum pro seriozne porovnani.",
      "Walk-forward pouzij pro nejrealistictejsi validaci.",
    ],
    recommendedDefault: "oos_split pro beznou iteraci, walk_forward pro finalni check.",
    withoutIt: "Muzes prijmout edge, ktery funguje jen na trenovacich datech.",
    bestPractices: ["Sweep kombinuj pouze s OOS/WF validaci."],
  },
  oosRatio: {
    id: "oosRatio",
    title: "OOS ratio",
    whatItMeans: "Podil dat vyhrazeny pro out-of-sample testovani.",
    whyItMatters: "Vyssi OOS pritvrzuje validaci, ale zmensuje trenovaci cast.",
    howToUse: ["Drz se rozsahu 0.20-0.30 pro vetsinu workflow."],
    recommendedDefault: "0.25",
    withoutIt: "Nemas oddelenou kontrolni cast dat a roste riziko overfittingu.",
    bestPractices: ["Nemen OOS ratio pri kazde iteraci bez explicitniho duvodu."],
  },
  wfFolds: {
    id: "wfFolds",
    title: "WF folds",
    whatItMeans: "Pocet walk-forward segmentu train/test.",
    whyItMatters: "Vice foldu dava robustnejsi pohled, ale prodluzuje vypocet.",
    howToUse: ["Pouzij 3-6 foldu jako kompromis kvalita/rychlost."],
    recommendedDefault: "4",
    withoutIt: "Validace muze byt moc hruba nebo naopak neprakticky pomala.",
    bestPractices: ["Pocet foldu sjednot v ramci jedne branch pred porovnanim runu."],
  },
  wfTestRatio: {
    id: "wfTestRatio",
    title: "WF test ratio",
    whatItMeans: "Podil testovaci casti v kazdem walk-forward okne.",
    whyItMatters: "Urcuje prisnost validace a stabilitu odhadu metrik.",
    howToUse: ["Typicky drzet mezi 0.15 a 0.25."],
    recommendedDefault: "0.20",
    withoutIt: "Muzes mit nevyvazenou train/test strukturu.",
    bestPractices: ["Udrzuj stejnou hodnotu v serii porovnavanych experimentu."],
  },
  minTradesGate: {
    id: "minTradesGate",
    title: "Gate min trades",
    whatItMeans: "Minimalni pocet obchodu pro povazovani runu za statisticky relevantni.",
    whyItMatters: "Prilis malo obchodu znamena velmi nestabilni metriky.",
    howToUse: ["Nastav tak, aby runy s malym vzorkem neprosly filtrem."],
    recommendedDefault: "20-30+",
    withoutIt: "Muzes vyhodnotit edge podle nahodneho souboru obchodu.",
    bestPractices: ["Vyssi gate pouzij pro strategie s velkou variabilitou vysledku."],
  },
  maxDdGate: {
    id: "maxDdGate",
    title: "Gate max DD %",
    whatItMeans: "Horni limit maximalniho drawdownu, ktery jeste akceptujes.",
    whyItMatters: "Chrani pred strategiemi, ktere jsou sice ziskove, ale rizikove neobchodovatelne.",
    howToUse: ["Nastav podle risk tolerance a kapitaloveho planu."],
    recommendedDefault: "20-30% podle stylu strategie.",
    withoutIt: "Run muze projit i pri neakceptovatelnem riziku.",
    bestPractices: ["Porovnavej DD gate s realnou psychologickou i kapitalovou toleranci."],
  },
  minPfGate: {
    id: "minPfGate",
    title: "Gate min PF",
    whatItMeans: "Minimalni profit factor potrebny pro schvaleni runu.",
    whyItMatters: "PF pod 1 znamena dlouhodobe neudrzitelny system.",
    howToUse: ["Nastav minimalni hranici kvality pro filtrovani slabych edge."],
    recommendedDefault: "1.1-1.3 podle trhu a nakladu.",
    withoutIt: "Muzes pripustit runy bez dostatecneho edge.",
    bestPractices: ["PF hodnot po zapocteni realistickych exekucnich nakladu."],
  },
  experimentHypothesis: {
    id: "experimentHypothesis",
    title: "Experiment hypothesis",
    whatItMeans: "Jednovetna formulace toho, co testujes a proc.",
    whyItMatters: "Pomaha drzet disciplinu a zpetne vysvetlit rozdily mezi runy.",
    howToUse: ["Napis testovatelnou vetu: podminka -> ocekavany dopad."],
    recommendedDefault: "Kratka konkretni veta bez obecnych frazi.",
    withoutIt: "Experimenty se meni v nahodne ladeni bez jasneho cile.",
    bestPractices: ["Pri zmene hypotezy vytvor novou branch."],
  },
  experimentTagsCsv: {
    id: "experimentTagsCsv",
    title: "Experiment tags (CSV)",
    whatItMeans: "Tagy pro rychle filtrovani a porovnavani runu.",
    whyItMatters: "Udrzis poradek i pri vetsim poctu iteraci.",
    howToUse: ["Pouzij kratke tagy: instrument, setup, verze logiky."],
    recommendedDefault: "3-5 tagu oddelenych carkou.",
    withoutIt: "Historie runu bude tezko prohledatelna.",
    bestPractices: ["Drz jednotny slovnik tagu napric tymem/projektem."],
  },
  experimentBranch: {
    id: "experimentBranch",
    title: "Run branch",
    whatItMeans: "Nazev vetve experimentu, pod kterou se runy seskupuji.",
    whyItMatters: "Umozni porovnavat podobne iterace mezi sebou.",
    howToUse: ["Pro kazdou vetsi zmenu logiky pouzij novou branch."],
    recommendedDefault: "main pro baseline, feature branch pro experimenty.",
    withoutIt: "Smichas nesouvisejici runy a ztratis kontext.",
    bestPractices: ["Nemen branch id behem jedne serie porovnavani."],
  },
  promoteOnPass: {
    id: "promoteOnPass",
    title: "Promote candidate when gates pass",
    whatItMeans: "Automaticky oznaci run jako kandidata pri splneni quality gates.",
    whyItMatters: "Zrychluje workflow rozhodovani, co ma smysl dal sledovat.",
    howToUse: ["Zapni, pokud mas gates nastaveny konzistentne a realisticky."],
    recommendedDefault: "Zapinat az po stabilizaci gate prahu.",
    withoutIt: "Budete rucne hodnotit vice runu bez priorizace.",
    bestPractices: ["Nezapinej, pokud jsou gate prilis benevolentni."],
  },
  sweepMode: {
    id: "sweepMode",
    title: "Sweep mode",
    whatItMeans: "Automaticke prohledavani parametru (none, random, grid).",
    whyItMatters: "Odhaluje citlivost edge na zmenu nastaveni.",
    howToUse: ["Pouzivej s OOS/WF validaci, ne se single run."],
    recommendedDefault: "random pro prvni pruzkum; grid az pro cileny narrowing.",
    withoutIt: "Muzes prehlednout nestabilitu edge napric parametry.",
    bestPractices: ["Nehodnot vysledky jen podle nejlepsi kombinace."],
  },
  sweepSamples: {
    id: "sweepSamples",
    title: "Sweep samples",
    whatItMeans: "Pocet testovanych kombinaci parametru ve sweepu.",
    whyItMatters: "Vice vzorku zlepsuje pokryti prostoru, ale zpomaluje vypocet.",
    howToUse: ["Zacni stredni hodnotou, zvysuj podle potreby detailu."],
    recommendedDefault: "24-48 podle komplexity strategie.",
    withoutIt: "Pruzkum muze byt prilis povrchni.",
    bestPractices: ["Drz stejny sample count pri porovnani dvou branchi."],
  },
  monteCarloEnabled: {
    id: "monteCarloEnabled",
    title: "Monte Carlo",
    whatItMeans: "Zapina simulace robustnosti equity a odhadu tail-risk.",
    whyItMatters: "Samotny jeden equity curve neukazuje rozsah moznych budoucich trajektorii.",
    howToUse: ["Pro seriozni vyhodnoceni edge nech Monte Carlo zapnute."],
    recommendedDefault: "Zapnuto pro vsechny kandidaty na produkci.",
    withoutIt: "Nevidis risk-of-ruin a hloubku krizovych scenaru.",
    bestPractices: ["Posuzuj i pesimisticke kvantily, ne jen median."],
  },
  monteCarloSims: {
    id: "monteCarloSims",
    title: "MC simulations",
    whatItMeans: "Pocet Monte Carlo simulaci.",
    whyItMatters: "Vice simulaci znamena stabilnejsi odhad distribuci rizika.",
    howToUse: ["Na rychly check staci nizsi pocet, na finalni rozhodnuti zvys."],
    recommendedDefault: "300-500",
    withoutIt: "Odhad risku muze byt statisticky sum a nahoda.",
    bestPractices: ["Pro porovnani runu pouzij stejny pocet simulaci."],
  },
  regimeEnabled: {
    id: "regimeEnabled",
    title: "Regime segmentation",
    whatItMeans: "Segmentuje vykon strategie podle trznich rezimu.",
    whyItMatters: "Ukaze, v jakych podminkach edge funguje nebo selhava.",
    howToUse: ["Zapni pri analyze stability edge napric trhem."],
    recommendedDefault: "Zapnout ve fazi hloubkove analyzy kandidata.",
    withoutIt: "Muzes prehlednout, ze edge funguje jen v jednom typu trhu.",
    bestPractices: ["Pouzij spolecne s delsi historii dat."],
  },
  portfolioEnabled: {
    id: "portfolioEnabled",
    title: "Portfolio backtest",
    whatItMeans: "Testuje strategii na vice instrumentech jako celek.",
    whyItMatters: "Diverzifikace muze snizit drawdown a zlepsit stabilitu equity.",
    howToUse: ["Zapni a vypln seznam instrumentu s vahami v JSON poli."],
    recommendedDefault: "Pouzij az po overeni edge na jednom trhu.",
    withoutIt: "Neodhadnes efekt diverzifikace nebo koncentracni riziko.",
    bestPractices: ["Validuj vahy a dostupnost dat pro kazdy instrument."],
  },
  portfolioInstrumentsJson: {
    id: "portfolioInstrumentsJson",
    title: "Portfolio instruments JSON",
    whatItMeans: "Detailni seznam instrumentu, timeframe, let a vah pro portfolio run.",
    whyItMatters: "Nespravny JSON nebo vahy = neplatne nebo zkreslene portfolio testy.",
    howToUse: ["Vkladej validni JSON pole s konzistentnimi klici."],
    recommendedDefault: "Zacni 2-3 instrumenty s jednoduchymi vahami.",
    withoutIt: "Portfolio rezim nebude odpovidat tvemu zamyslenemu slozeni.",
    bestPractices: ["Pred runem validuj, ze vahy davaji smysl a data existuji."],
  },
  executionEnabled: {
    id: "executionEnabled",
    title: "Realistic execution model",
    whatItMeans: "Zapocita realne exekucni frikce: spread, slippage podle volatility, latenci.",
    whyItMatters: "Priblizuje backtest realnemu market fill chovani.",
    howToUse: ["Zapni pro seriozni evaluaci a nastav navazna pole exekuce."],
    recommendedDefault: "Zapnuto pred finalnim rozhodnutim o edge.",
    withoutIt: "Vysledky jsou obvykle nadhodnocene.",
    bestPractices: ["Kalibruj podle realnych fill dat nebo broker reportu."],
  },
  spreadBps: {
    id: "spreadBps",
    title: "Spread (bps)",
    whatItMeans: "Transakcni penalizace ve formatu basis points.",
    whyItMatters: "I maly spread muze vyrazne zhorsit net performance.",
    howToUse: ["Nastav realisticky podle instrumentu a denni doby exekuce."],
    recommendedDefault: "0.5 bps jako baseline, dle trhu upravit.",
    withoutIt: "Backtest podhodnoti naklady vstupu/vystupu.",
    bestPractices: ["U mene likvidnich trhu pouzij konzervativnejsi spread."],
  },
  slippageVolMult: {
    id: "slippageVolMult",
    title: "Slip x vol",
    whatItMeans: "Nasobic slippage citlivy na volatilitu.",
    whyItMatters: "Pri vysoke volatilite by mel byt skluz horsi nez v klidu.",
    howToUse: ["Zacni na 1.0 a testuj konzervativni varianty."],
    recommendedDefault: "1.0",
    withoutIt: "Nedocenis riziko v turbulentnich obdobich.",
    bestPractices: ["Porovnej vysledek pri 1.0 vs 1.5 pro stress test."],
  },
  latencyBars: {
    id: "latencyBars",
    title: "Latency bars",
    whatItMeans: "Kolik baru zpozdeni je mezi signalem a exekuci.",
    whyItMatters: "Latence casto meni vstupni cenu a tim i edge.",
    howToUse: ["Nastav podle realne technologie a exekucniho stacku."],
    recommendedDefault: "0 pro ideal, 1+ pro realisticky stress test.",
    withoutIt: "Strategie muze vypadat lepe, nez je realne dosazitelne.",
    bestPractices: ["U intradennich setupu latenci vzdy otestuj."],
  },
  forwardBridgeEnabled: {
    id: "forwardBridgeEnabled",
    title: "Forward testing bridge",
    whatItMeans: "Most mezi backtest baseline a navaznym paper/live shadow sledovanim.",
    whyItMatters: "Pomaha overit, jestli edge drzi i po backtest fazi.",
    howToUse: ["Zapni v execution model sekci pro prechod do forward rezimu."],
    recommendedDefault: "Zapnout pri prechodu kandidata do monitorovaneho provozu.",
    withoutIt: "Chybi navaznost mezi research a post-backtest validaci.",
    bestPractices: ["Dokumentuj baseline equity pri kazdem bridge runu."],
  },
  forwardBridgeMode: {
    id: "forwardBridgeMode",
    title: "Bridge mode",
    whatItMeans: "Typ shadow rezimu (paper/live) pro forward porovnani.",
    whyItMatters: "Urcuje uroven realismu i rizika po backtestu.",
    howToUse: ["Paper shadow pro bezpecny start, live shadow pro blizsi realitu."],
    recommendedDefault: "paper_shadow",
    withoutIt: "Nebudes mit kontrolovany proces prechodu k realne exekuci.",
    bestPractices: ["Do live shadow prejdi az po stabilnim paper vysledku."],
  },
  forwardBridgeBaselineEquity: {
    id: "forwardBridgeBaselineEquity",
    title: "Baseline equity",
    whatItMeans: "Referencni equity hodnota pro porovnani ve forward bridge.",
    whyItMatters: "Bez baseline je tezke merit, jestli se vykon zlepsuje nebo degraduje.",
    howToUse: ["Nastav posledni relevantni equity z overeneho backtestu."],
    recommendedDefault: "Stejna jako final equity baseline runu.",
    withoutIt: "Forward srovnani nebude konzistentni.",
    bestPractices: ["Pri kazde nove branchi resetuj baseline explicitne."],
  },
};

export function getParamFallbackHelp(paramName: string, source: "PARAMS" | "VIEW_PARAMS"): BacktestFieldHelp {
  const normalized = paramName.replace(/_/g, " ");
  const prettyName = normalized.charAt(0).toUpperCase() + normalized.slice(1);
  const isView = source === "VIEW_PARAMS";
  return {
    id: `dynamic-${source}-${paramName}`,
    title: prettyName,
    whatItMeans: `${source} parametr definovany v Python kodu.`,
    whyItMatters:
      "Bez dokumentace parametru je easy udelat tuning naslepo a ztratit konzistenci mezi runy.",
    howToUse: [
      "Nastav hodnotu podle hypotezy a testuj po malych krocich.",
      "Po kazde zmene zkontroluj dopad na quality gates a robustnost.",
      isView
        ? "Ve View modu pouzij parametr pro vizualni kontrolu logiky."
        : "V backtestu parametr men pouze s jasnym duvodem.",
    ],
    recommendedDefault: "Pouzij default z Python kodu, dokud nemas duvod menit.",
    withoutIt: "Muzes nechtene preladit strategii bez pochopeni dopadu.",
    bestPractices: [
      "Dopln metadata v PARAMS_META/VIEW_PARAMS_META pro detailni wiki vysvetleni.",
      "Pri tuning iteracich zapisuj branch, tags a hypothesis.",
    ],
  };
}
